schemaVersion: 2.2.0
metadata:
  name: cloud-dev-images
attributes:
  controller.devfile.io/storage-type: ephemeral
components:
  - name: tools
    container:
      image: quay.io/devfile/universal-developer-image:ubi8-latest
      memoryRequest: 1Gi
      memoryLimit: 8Gi
      cpuLimit: '4'
      cpuRequest: '0.5'
