name: golang-vscode-startup

on:
  workflow_dispatch:
    inputs:
      sandboxToken:
        description: "Red Hat Developer Sandbox Token"
        required: true
        type: string

env:
  CLOUD_DEV_IMAGE: quay.io/mloriedo/cloud-dev-images:golang
  EDITOR_IMAGE: quay.io/che-incubator/che-code:insiders
  CLUSTER_URL: https://api.sandbox-m2.ll9k.p1.openshiftapps.com:6443

jobs:
  vscode-startup:
    runs-on: ubuntu-latest
    steps:
      - name: Add Mask
        run: echo "::add-mask::${{ inputs.sandboxToken }}"
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Dev Sandbox
        run: oc login --token=${{ inputs.sandboxToken }} --server=${{ env.CLUSTER_URL }}
      - name: Run Test
        run: ${PWD}/__tests__/test-editor-startup-in-image.sh
