name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          regisry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}
      -
        name: Build and push alpine
        uses: docker/build-push-action@v4
        with:
          context: alpine
          push: true
          tags: quay.io/mloriedo/cloud-dev-images:alpine
      -
        name: Build and push busybox
        uses: docker/build-push-action@v4
        with:
          context: busybox 
          push: true
      -
        name: Build and push docker
        uses: docker/build-push-action@v4
        with:
          context: docker
          push: true
          tags: quay.io/mloriedo/cloud-dev-images:docker

