name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to quay.io
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}
      -
        name: Build and push alpine
        uses: docker/build-push-action@v4
        with:
          context: alpine
          push: true
          tags: quay.io/mloriedo/cloud-dev-images:alpine
      -
        name: Build and push busybox
        uses: docker/build-push-action@v4
        with:
          context: busybox 
          push: true
          tags: quay.io/mloriedo/cloud-dev-images:busybox
      -
        name: Build and push docker
        uses: docker/build-push-action@v4
        with:
          context: docker
          push: true
          tags: quay.io/mloriedo/cloud-dev-images:docker
      -
        name: Build and push fedora
        uses: docker/build-push-action@v4
        with:
          context: fedora
          push: true
          tags: quay.io/mloriedo/cloud-dev-images:fedora
      -
        name: Build and push golang
        uses: docker/build-push-action@v4
        with:
          context: golang
          push: true
          tags: quay.io/mloriedo/cloud-dev-images:golang
      -
        name: Build and push openjdk
        uses: docker/build-push-action@v4
        with:
          context: openjdk
          push: true
          tags: quay.io/mloriedo/cloud-dev-images:openjdk
      -
        name: Build and push ubi8
        uses: docker/build-push-action@v4
        with:
          context: ubi8
          push: true
          tags: quay.io/mloriedo/cloud-dev-images:ubi8
      -
        name: Build and push ubi9
        uses: docker/build-push-action@v4
        with:
          context: ubi9
          push: true
          tags: quay.io/mloriedo/cloud-dev-images:ubi9
      -
        name: Build and push ubuntu
        uses: docker/build-push-action@v4
        with:
          context: ubuntu
          push: true
          tags: quay.io/mloriedo/cloud-dev-images:ubuntu

